name: flan
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  go_router: ^6.0.2
  flutter_screenutil: ^5.6.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  http: ^0.13.5
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  image_picker: ^0.8.6+1
  carousel_slider: ^4.2.1
  animations: ^2.0.7
  flutter_colorpicker: ^1.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fpdart: ^0.4.0
  firebase_core: ^2.5.0
  google_mobile_ads: ^2.3.0
  permission_handler: ^10.2.0
  contacts_service: ^0.6.3
  zalo_flutter: ^0.0.5
  share_plus: ^6.3.1
  firebase_messaging: ^14.2.4
  flutter_local_notifications: ^8.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.11.0


flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: SCDream
      fonts:
        - asset: fonts/SCDream1.otf
          weight: 100
        - asset: fonts/SCDream2.otf
          weight: 200
        - asset: fonts/SCDream3.otf
          weight: 300
        - asset: fonts/SCDream4.otf
          weight: 400
        - asset: fonts/SCDream5.otf
          weight: 500
        - asset: fonts/SCDream6.otf
          weight: 600
        - asset: fonts/SCDream7.otf
          weight: 700
        - asset: fonts/SCDream8.otf
          weight: 800
        - asset: fonts/SCDream9.otf
          weight: 900